### ISSUE TITLE
get_all_queries returns values from different domain or namespace 

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/snapquery#44]
namespaces or domains sharing the same prefix are loaded both with the regex whitecard `%` as part of the parameter values.
Is this intended?
Currently it is not guaranteed that for the given domain and namespace only queries with the same domain and namespace are returned. 
https://github.com/WolfgangFahl/snapquery/blob/310ee45db45358577af6c1180ef5d2434c40bbc6/snapquery/snapquery_core.py#L1146-L1151

https://github.com/WolfgangFahl/snapquery/blob/310ee45db45358577af6c1180ef5d2434c40bbc6/snapquery/snapquery_core.py#L1164-L1167

**Comment by WolfgangFahl** [comment]
is that not only a usage problem? In which case does this problem manifest itself (situation/action/expected result)? and what shall we do about it? Currently this like query is only used in the search and if the search is not hierarchical that is IMHO o.k.

**Comment by tholzheim** [comment]
The Namespace column offers a dropdown selection for possible Namespaces. But selecting a namespace which is a prefix of another namespace results in a Table which contains more than the selected namespace.

See for example:
> ![image](https://github.com/user-attachments/assets/60cf78b1-459d-4d64-849a-da22eb8452da)

**Comment by WolfgangFahl** [comment]
perform_search is changed - do we also want to change get_all_queries?
